/*
 * This file was automatically generated by EvoSuite
 * Mon Feb 27 06:12:51 GMT 2017
 */

package org.cs362.dominion;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.ArrayList;
import org.cs362.dominion.Baron;
import org.cs362.dominion.Board;
import org.cs362.dominion.Player;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Baron_ESTest extends Baron_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Baron baron0 = new Baron();
      ArrayList<Player> arrayList0 = new ArrayList<Player>();
      Board board0 = new Board();
      // Undeclared exception!
      try { 
        baron0.Action(arrayList0, (Player) null, board0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.cs362.dominion.Baron", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Board board0 = new Board();
      Player player0 = new Player("3", false);
      Baron baron0 = new Baron();
      baron0.Action((ArrayList<Player>) null, player0, board0);
      assertEquals("3", player0.getName());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Baron baron0 = new Baron();
      ArrayList<Player> arrayList0 = new ArrayList<Player>();
      Player player0 = new Player("", true);
      Board board0 = new Board();
      // Undeclared exception!
      try { 
        baron0.Action(arrayList0, player0, board0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }
}
